name: Main

on: 

  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      resourceGroup:
        description: 'Azure resource group used for deployment'     
        required: true
        default: 'my-resource-group-1' 
        type: string
      ipAddr:
        description: 'Load balancer IP Address'
        required: true
        default: 20.216.130.193
        type: string

jobs:

  init:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: |
          echo "::set-output name=date::$(date +'%Y%m%dT%H%M%S')"
      - name: Init resource group name
        id: rg
        run: |
          RG_INPUT=${{ github.event.inputs.resourceGroup }}
          echo "::set-output name=value::${RG_INPUT:-my-resource-group-1}"
      - name: Init ip address
        id: ipAddr
        run: |
          VM_TYPE_INPUT=${{ github.event.inputs.ipAddr }}
          echo "::set-output name=value::${VM_TYPE_INPUT:-20.216.130.193}"
    outputs:
      rg: ${{ steps.rg.outputs.value }}
      vmId: ${{ steps.date.outputs.value }}
      ipAddr: ${{ steps.ipAddr.outputs.value }}

  call-build:
    uses: ./.github/workflows/maven-build.yml
    secrets:
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}

  call-azure-deploy:
    uses: ./.github/workflows/vm-deploy.yml
    with:
      resourceGroup: ${{ needs.init.outputs.rg }}
      vmId: ${{ needs.init.outputs.vmId }}
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      AZURE_ARTIFACTS_LOCATION: ${{ secrets.AZURE_ARTIFACTS_LOCATION }}
      AZURE_ARTIFACTS_LOCATION_SAS_TOKEN: ${{ secrets.AZURE_ARTIFACTS_LOCATION_SAS_TOKEN }}
      VM_ADMIN_USERNAME: ${{ secrets.VM_ADMIN_USERNAME }}
      VM_ADMIN_PUBLIC_KEY: ${{ secrets.VM_ADMIN_PUBLIC_KEY }}
    needs: [init, call-build]
    
  call-validation:
    uses: ./.github/workflows/validation.yml
    with:
      ipAddr: ${{ needs.init.outputs.ipAddr }}
    needs: [init, call-azure-deploy]