name: Main

on: 

  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      resourceGroup:
        description: 'Azure resource group used for deployment'     
        required: true
        default: 'my-resource-group-1' 
        type: string
      projectName:
        description: 'Azure resources will be prefixed with this value'     
        required: true
        default: 'test1' 
        type: string

jobs:

  call-build:
    uses: ./.github/workflows/maven-build.yml
    secrets:
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}

  call-azure-deploy:
    steps:
      - name: Init resource group name
        id: rg
        run: |
          RG_INPUT=${{ github.event.inputs.resourceGroup }}
          echo "::set-ouput rg=value::${RG_INPUT:-"my-resource-group-1"}"
      - name: Init project name
        id: project
        run: |
          PROJECT_NAME_INPUT=${{ github.event.inputs.projectName }}
          echo "::set-ouput project=value::${PROJECT_NAME_INPUT:-"test1"}""
    uses: ./.github/workflows/azure-deploy.yml
    with:
      resourceGroup: ${{ steps.rg.outputs.value }}
      projectName: ${{ steps.project.outputs.value }}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      AZURE_ARTIFACTS_LOCATION: ${{ secrets.AZURE_ARTIFACTS_LOCATION }}
      AZURE_ARTIFACTS_LOCATION_SAS_TOKEN: ${{ secrets.AZURE_ARTIFACTS_LOCATION_SAS_TOKEN }}
      VM_ADMIN_USERNAME: ${{ secrets.VM_ADMIN_USERNAME }}
      VM_ADMIN_PUBLIC_KEY: ${{ secrets.VM_ADMIN_PUBLIC_KEY }}
    needs: call-build

  call-setup-env:
    uses: ./.github/workflows/setup-env.yml
    needs: call-azure-deploy