name: Main

on: 

  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      resourceGroup:
        description: 'Azure resource group used for deployment'     
        required: true
        default: 'my-resource-group-1' 
        type: string
      vmType:
        description: 'Vm Type'     
        required: true
        default: 'staging' 
        type: string

jobs:

  init:
    runs-on: ubuntu-latest
    steps:
      - name: Init resource group name
        id: rg
        run: |
          RG_INPUT=${{ github.event.inputs.resourceGroup }}
          echo "::set-output name=value::${RG_INPUT:-my-resource-group-1}"
      - name: Init vm type
        id: vmType
        run: |
          VM_TYPE_INPUT=${{ github.event.inputs.vmType }}
          echo "::set-output name=value::${VM_TYPE_INPUT:-staging}"
    outputs:
      rg: ${{ steps.rg.outputs.value }}
      vmType: ${{ steps.vmType.outputs.value }}

  call-build:
    uses: ./.github/workflows/maven-build.yml
    secrets:
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}

  call-azure-deploy:
    uses: ./.github/workflows/vm-deploy.yml
    with:
      resourceGroup: ${{ needs.init.outputs.rg }}
      vmType: ${{ needs.init.outputs.vmType }}
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      AZURE_ARTIFACTS_LOCATION: ${{ secrets.AZURE_ARTIFACTS_LOCATION }}
      AZURE_ARTIFACTS_LOCATION_SAS_TOKEN: ${{ secrets.AZURE_ARTIFACTS_LOCATION_SAS_TOKEN }}
      VM_ADMIN_USERNAME: ${{ secrets.VM_ADMIN_USERNAME }}
      VM_ADMIN_PUBLIC_KEY: ${{ secrets.VM_ADMIN_PUBLIC_KEY }}
    needs: [init, call-build]

  # debug:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Show ip address
  #       run: echo "ip addr ${{ needs.call-azure-deploy.outputs.ipAddr }}"    
  #   needs: call-azure-deploy
    
  call-validation:
    uses: ./.github/workflows/validation.yml
    with:
      ipAddr: ${{ needs.call-azure-deploy.outputs.ipAddr }}
    needs: call-azure-deploy