

name: Azure VM deploy

on: 
  workflow_call:
    inputs:
      resourceGroup:
        type: string
        required: true
      vmType:
        type: string
        required: true
    secrets:
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_CREDENTIALS:
        required: true
      AZURE_STORAGE_KEY:
        required: true
      AZURE_ARTIFACTS_LOCATION:
        required: true
      AZURE_ARTIFACTS_LOCATION_SAS_TOKEN:
        required: true
      VM_ADMIN_USERNAME:
        required: true
      VM_ADMIN_PUBLIC_KEY:
        required: true

jobs:

  deploy: 
    runs-on: ubuntu-latest
    steps:

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: List application
        id: app
        uses: azure/CLI@v1
        with:
          inlineScript: |
              version=$(az storage file list --account-key ${{ secrets.AZURE_STORAGE_KEY }} --account-name ovistorageaccount --share-name app --query "[].{name:name}" --output tsv)
              echo "::set-output name=version::$version"

      - name: App version
        run: echo ${{ steps.app.outputs.version }} 

      - name: Remove vm extension
        uses: azure/CLI@v1
        continue-on-error: true
        with:
          inlineScript: |
              az vm extension delete -g ${{ inputs.resourceGroup }} --vm-name file-serice-vm-${{ inputs.vmType }} -n remote-script

      - name: Deploy infrastructure (ARM)
        id: infra
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ inputs.resourceGroup }}
          template: azure/infrastructure.json
          parameters:
            _artifactsLocation="${{ secrets.AZURE_ARTIFACTS_LOCATION }}"
            _artifactsLocationSasToken="${{ secrets.AZURE_ARTIFACTS_LOCATION_SAS_TOKEN }}"            
            vmType=${{ inputs.vmType }}
            adminUsername=${{ secrets.VM_ADMIN_USERNAME }}
            adminPublicKey="${{ secrets.VM_ADMIN_PUBLIC_KEY }}"
            application=${{ steps.app.outputs.version }}            

      - name: Add VM to inbound nat rule
        uses: azure/CLI@v1
        with:
          inlineScript: |
              az network nic ip-config inbound-nat-rule add --ip-config-name ipconfig1 --resource-group ${{ inputs.resourceGroup }} --lb-name file-service-lb  --nic-name file-service-nic-${{ inputs.vmType }} --inbound-nat-rule file-service-net-rule-${{ inputs.vmType }}